[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["curl -fsSL https://bun.sh/install | bash", "~/.bun/bin/bun install"]

[phases.build]
cmds = ["~/.bun/bin/bun run build"]

[start]
cmd = "node dist/main"
